name: Node.js CI Checks

# Trigger on pull requests targeting the 'main' branch
on:
  pull_request:
    branches: [ main ] # Changed from code2.0 to main - adjust if your main branch has a different name

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Using LTS version is generally recommended unless you need a specific newer feature
        node-version: [18.x] # Changed from 22.19.0 to 18.x (LTS) - adjust if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 (latest major version)

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build command
        run: npm run build

      - name: Run lint command
        # Ensure you have a "lint" script in your package.json
        run: npm run lint