name: Node.js CI Checks  # Name of the workflow

on:
  pull_request:         # Trigger the workflow on pull requests
    branches: [code2.0]  # Specify the branch(es) to trigger on (e.g., main, master)

jobs:
  build_and_lint:       # Name of the job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    strategy:
      matrix:
        node-version: [22.19.0] # Specify Node.js version(s) to use

    steps:
    - name: Checkout repository # Step to check out your code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }} # Step to set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'        # Cache npm dependencies for faster builds

    - name: Install dependencies # Step to install project dependencies
      run: npm ci             # 'ci' is generally recommended for CI environments

    - name: Run build command   # Step to build the project
      run: npm run build

    # Add this step for linting.
    # Note: Your package.json doesn't explicitly define a 'lint' script.
    # You might need to add one, e.g., "lint": "eslint src/**/*.js"
    # Or adjust the command below if you use a different linting tool/command.
    - name: Run lint command    # Step to lint the code
      run: npm run lint       # Assumes you have an 'npm run lint' script